sonar.projectKey=jetson-ai-lab_jetson-containers
sonar.organization=jetson-ai-lab

sonar.sources=jetson_containers,packages,scripts
sonar.tests=tests,test_suite
sonar.python.version=3.10,3.11,3.12

sonar.exclusions=**/Dockerfile*,**/*.patch,logs/**,data/**,deprecated/**,venv/**,**/__pycache__/**,docs/**,.github/**

sonar.sourceEncoding=UTF-8
